# nixpacks.toml
# Configuration for building the Splattr VitePress documentation site.

[phases.setup]
nixPkgs = ['nodejs_20']
packages = ['pnpm']

[phases.install]
cmds = ['npm install -g corepack', 'corepack enable', 'corepack prepare pnpm@latest --activate', 'pnpm install']

[phases.build]
cmd = "pnpm run docs:build"

[start]
cmd = "npx serve docs/.vitepress/dist -s"